name: "Liverpool FC"
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/post-bot.yml
    with:
      bskyHandle: "lfcbot.bsky.social"
      mastodonHandle: "@lfc@sportsbots.xyz"
      mastodonAccountId: "109787827684130095"
      altCardImg: "https://pbs.twimg.com/profile_images/1856268307868844032/lbdn4-vK_400x400.jpg"
    secrets:
      bskyPassword: ${{ secrets.LFC_BSKY_PASSWORD }}