name: "NFL"
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/post-bot.yml
    with:
      bskyHandle: "nflbot.bsky.social"
      mastodonHandle: "@nfl@sportsbots.xyz"
      mastodonAccountId: "109616443942149309"
    secrets:
      bskyPassword: ${{ secrets.NFL_BSKY_PASSWORD }}