name: "Ravens"
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/post-bot.yml
    with:
      bskyHandle: "ravensbot.bsky.social"
      mastodonHandle: "@ravens@sportsbots.xyz"
      mastodonAccountId: "109700148957607619"
    secrets:
      bskyPassword: ${{ secrets.RAVENS_BSKY_PASSWORD }}